### ISSUE TITLE
開発環境: テスト環境の構築とCI/CD統合

### ISSUE THREAD

**Issue by YunosukeYoshino** [YunosukeYoshino/elysiajs-demo#5]
## 概要
現在のCMSプロジェクトにはテストとCI/CD設定が不足しています。安定したコードベースを維持し、継続的な開発を支援するためには、適切なテスト環境とCI/CD設定が重要です。

### テスト環境の構築
- Bunのテストランナーを使用したテスト環境
- ユニットテスト: 
  - ルーターとミドルウェアのテスト
  - モデルとビジネスロジックのテスト
- 統合テスト:
  - APIエンドポイントのテスト
  - ユーザー認証フローのテスト
- E2Eテスト（オプション）

### テストデータとフィクスチャ
- テスト用のデータベースセットアップ
- テストフィクスチャの作成
- テスト環境向けのシードデータ

### CI/CD設定
- GitHub Actionsを使用したCI設定:
  - プルリクエスト時に自動テスト実行
  - コードカバレッジレポートの生成
  - リンターとフォーマッターの実行
- CD設定:
  - 自動デプロイフロー
  - デプロイプレビュー環境

## 必要なパッケージ
- Bunテストランナー
- ミドルウェアのモックとスタブのためのユーティリティ
- コードカバレッジツール

## 設定ファイル例
```yaml
# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Run linter
      run: bun run lint
    
    - name: Run tests
      run: bun test
    
    - name: Check types
      run: bun run type-check
```

## 技術的な考慮事項
- テスト環境でのデータベースの分離
- シークレットやAPIキーの安全な管理
- テストの実行速度最適化

## 優先度
高（安定した開発環境を確保するため）
